Feature/#40 automatic job query
CorrelAid/genesis-python pull request #70
Opened 2022-09-19 18:00 UTC by felixschmitz

feature branch for starting a job query regarding large data files

2022-09-19 20:55 UTC, pmayd requested changes
Hier sehe ich noch einigen Arbeitsbedarf, vor allem die Funktion `_jobs_params` scheint mir noch relativ fehleranfällig bzw. zum Teil unsinnig? Da sollten wir nochmal die while-Schleife anschauen. Weiter unten dann auch einige Aufräumarbeit und debug prints zu entfernen

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +            if type(new_params) == dict:
eine Typabfrage macht man besser mit `isinstance(new_params, dict)`

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        dict: new dict to start a job
Würde hier "new request params dict to start a job" schreiben, damit klar ist, wofür das dict verwendet werden soll

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    while job_bool.lower() not in positive + negative:
Zwei Listen mit + zu verknüpfen legt jedes Mal eine neue Liste an, daher wäre es etwas schöner, eine neue Variable `possible_answers` anzulegen, die die beiden Listen nur einmal verknüpft

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        logger.warning(
warm wird das Warning hier innerhalb der while loop ausgegeben? Das ändert sich doch nicht?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    while job_bool.lower() not in positive + negative:
Was ist nochmal die Idee der `while` Schleife?? Hier wird doch nur einmal auf ein `input` gewartet, was zudem das Program endlos blockiert, danach wird die Schleife doch gar nicht neu gestartet? Also in jedem Fall wird der Code doch nur ein einziges Mal durchlaufen, da kannst du doch die ganze while Schleife weglassen? Du wartest einmalig darauf, dass der User etwas eingibt und wenn es nicht passt, wird automatisch `job_bool` auf False gesetzt

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    params.update({"job": "true"})
warum wird jetzt "job" immer auf true gesetzt obwohl weiter oben die ganze Idee der while Schleife doch darin besteht, den User das bestimmen zu lassen? Aktuell würde die Funktion ja einfach immer einen Job starten egal was der User eingibt ,auch bei nein?!

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        params = None
Warum soll das params dict hier gelöscht werden? Sollte man das übergebene dict nicht unverändert lassen?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        params = None
Das Problem ist hier dass dein return value dann auc hnicht stimmt, weil die Funktion kein dict mehr zurückgibt. Ich würde vorschlagen, eher "job" auf "false" zu setzen und das in der parent function abzufragen, also nicht auf `isinstance(job_params, dict)` prüfen sondern auf `if job_params.get("job") == "true"`, denn wir wollen ja nur den Job anstoßen, wenn der Wert auf "true" gesetzt wurde

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    """
interne Funktionen müssen nicht dokumentiert werden ;)

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    job_true_response = json.loads(response)
wenn doch hier JSON gebraucht wird, warum nicht load_data mit as_json=True aufrufen?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +                # jobs_response = load_data(endpoint=endpoint, method=method, params=new_params, as_json=True)
warum nicht diese Funktion nutzen?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +                print(response)
wir wollten keine prints nutzen, sondern logger, oder?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    print(response.json())
siehe oben, logger?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +) -> json:
json ist kein gültiger return value da kein Python type

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        time.sleep(20)
das finde ich immer noch sehr unschön, wir warten hier unnötigerweise immer 20 Sekunden

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +            catalogue_state,
der initiale Status ist ´None` und wird daher zu keiner sinnvollen/leeren Ausgabe führen

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        catalogue_response = json.loads(
Bitte load_data nutzen

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        time.sleep(20)
Das muss eigentlich raus hier? Ist ja auch am Ende

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        time.sleep(20)
Und bitte nicht hardgecoded sondern als CONSTANT/global Var im header oben

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        """
aufräumen?

2022-09-19 20:55 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        print("test1")
debug prints? aufräumen?

2022-10-04 15:02 UTC, felixschmitz commented
@pmayd Kannst du dir das finale Ergebnis bitte ansehen?

2022-10-04 17:11 UTC, MarcoHuebner commented on src/pygenesis/http_helper.py
> +    logger.info(
siehe oben/ könnte man mMn in eine Nachricht packen, da die ID ja identisch ist/ keine neuen Informationen entstanden sind.

2022-10-04 17:11 UTC, MarcoHuebner commented on tests/test_http_helper.py
> +    try:
Siehe oben: `pytest.raises`

2022-10-04 19:26 UTC, pmayd requested changes
Ich habe versucht zu verstehen, was hier genau passiert, aber der Code ist wieder sehr anders als zu dem letzten Treffen wo wir uns deinen Code angesehen hatten. Damals war ja alles in einer Funktion und die Daten wurden auch gedownloaded, jetzt scheint es so, als ob es nur noch den Job-Teil gibt aber der eigentliche Download komplett rausgeflogen ist? Das finde ich schade und war mir so nicht klar, da sollten wir unbedingt nachbessern. Es ist ja nicht so schwer, noch eine Funktion anzubieten, die den endpunkt data/resultfile aufruft. Das können wir von mir aus sogar innerhalb der Methode machen, auch wenn ich für zwei getrennte Funktionen argumentiert habe.

Das Hauptproblem ist aber, das der User aktuell nur über eine logger.info oder .warning über die job-ID informiert wird, bzw. irgendwo versteckt als return value in der response. Hier müssen wir schauen, dass das nicht verloren geht und dass der Benutzer sinnvoll durch die weiteren Handlungen geführt wird.

Ich weiß dir fehlt vermutlich die Zeit um daran weiterzuarbeiten daher ist das für mic hok ich würde den PR aber auf jeden Fall noch erweitern wollen bis wir auch den tatsächlichen Download implementiert haben.

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        if response_status_code == 98:
`98` ist eine "magical number" und sollte als globale Konstante oben definiert sein, warum gerade 98 etc. Wenn sich das mal ändert, ist es schwierig wiederzufinden, daher wird sowas als globale Konstante nach den imports für das Modul festgehalten, z.b. sowas wie `DESTATIS_JOB_STATUS_CODE` oder so

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +            jobs_response = load_data(
brauchen wir hier `load_data` oder reicht nicht `get_data_from_endpoint` Problem ist das load_data ja auch wieder get_data_from_endpoint aufruft, aber zusätzlich cacht.

Wenn ich richtig denke, brauchen wir hier keinen Cache, denn:
1. Wenn noch nicht gecacht, dann wird der Job angestoßen und die Datei gedownloaded, dann wird das erste Mal ein Cache für die EVAS/name angelegt. 
2. Der nächste Call von load_data liefert dann einen Cache hit, d.h. es wird kein neuer Job angestoßen. Wenn also ein neuer Job angestoßen wird, dann immer nur, weil es zu dieser EVAS oder mit den Parametern noch keinen hit im cache gab, dann brauchen wir aber auch den Download, d.h. wir brauchen hier kein load_data oder?

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        "Der Status des Jobs kann über den catalogue/jobs Endpunkt "
Wieso weisen wir hier auf einen Endpunkt hin statt eine Funktion? Wir wollen doch dem User die Funktion anbieten und keinen Destatis Endpunkt?

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +        "Wenn der Status des Jobs 'Fertig' ist, können die Daten über den data/resultfile Endpunkt "
Siehe oben, dafür sollten wir doch FUnktionen haben?

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +            return str(_jobs_job_id(jobs_response))
Was ist die Idee hinter diesem return value? `load_data` ruft ja `get_data_from_endpoint` auf und erwartet eigentlich die Daten als raw text zurück und cacht diese. Jetzt bekommen wir hier dann eine Job-ID zurück, heißt das, wir müssen auch über das Caching in load_data nachdenken bzw. diesen Fall handeln?

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +    try:
try-except sollte immer nur den kritischen Teil umschließen nicht den gesamten Code Block. Wo tritt hier der JSONDecode Error auf?

2022-10-04 19:26 UTC, pmayd commented on src/pygenesis/http_helper.py
> +            return str(_jobs_job_id(jobs_response))
Der Name ist auch sehr irreführend. `jobs_job_id` liest zwar die Job ID aus macht damit aber gar nichts, oder? Zurückgegeben wird ja dennoch die ursprüngliche Response? Das ist irgendwie nicht sauber, warum brauchen wir das? Nur um den User über die Job-ID zu informieren?

2022-10-05 21:17 UTC, pmayd approved these changes

2022-10-08 09:55 UTC, MarcoHuebner approved these changes
Removed one comment (see next commit), tests running, will use some time after my vacation to improve test coverage & ensure meaningful tests (as mentioned previously for helloworld and profile)

2022-10-08 09:55 UTC, MarcoHuebner commented on src/pygenesis/http_helper.py
> +            # logger.warning(destatis_status_content)
Würde den Kommentar entfernen (pushe gleich einen kleinen commit)

2022-10-08 19:32 UTC, merged